// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4NBMrpHWjuV1LiIJFLcCAO9cUAo6tr2w',
    appId: '1:658759085303:web:b4ed44f471de400ab877f2',
    messagingSenderId: '658759085303',
    projectId: 'petassist-76989',
    authDomain: 'petassist-76989.firebaseapp.com',
    storageBucket: 'petassist-76989.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuu2DLXOey5PIUgbhVmAKWHwUlIywRUXo',
    appId: '1:658759085303:android:fe6f08a78866a16fb877f2',
    messagingSenderId: '658759085303',
    projectId: 'petassist-76989',
    storageBucket: 'petassist-76989.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrQd2aeF2WxetdDpqtZFf0IGg_tZA8uQI',
    appId: '1:658759085303:ios:d2540ee39b18c372b877f2',
    messagingSenderId: '658759085303',
    projectId: 'petassist-76989',
    storageBucket: 'petassist-76989.firebasestorage.app',
    iosBundleId: 'com.example.petassist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrQd2aeF2WxetdDpqtZFf0IGg_tZA8uQI',
    appId: '1:658759085303:ios:d2540ee39b18c372b877f2',
    messagingSenderId: '658759085303',
    projectId: 'petassist-76989',
    storageBucket: 'petassist-76989.firebasestorage.app',
    iosBundleId: 'com.example.petassist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4NBMrpHWjuV1LiIJFLcCAO9cUAo6tr2w',
    appId: '1:658759085303:web:997598cbef2ee1d6b877f2',
    messagingSenderId: '658759085303',
    projectId: 'petassist-76989',
    authDomain: 'petassist-76989.firebaseapp.com',
    storageBucket: 'petassist-76989.firebasestorage.app',
  );
}
